<a href="https://colab.research.google.com/github/Madhavmurari/Pytorch-Learning/blob/main/pytorch_fundametal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


## Intoduction to Tensor

### creating tensors

In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get Tensor Back as Python int
scalar.item()

7

In [ ]:
#Vector
vector=torch.tensor([4,5])
vector


tensor([4, 5])

In [ ]:
vector.ndim



1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
#Matrix
Matrix=torch.tensor([[7,8],
                     [4,5]])
Matrix


tensor([[7, 8],
        [4, 5]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix[1]

tensor([4, 5])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor

Tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],[[7,8,9],[4,5,6],[1,2,3]]])

In [ ]:
Tensor.shape

torch.Size([2, 3, 3])

In [ ]:
Tensor[1,0]

tensor([7, 8, 9])

### Random Tensor

Why Random Tensor?

Random Tensor are important beacause the way many Neuarl Network work learn is that They start with tensor full of random number and then update the random number to represent data in better way.

`strat with random number -> Look at data -> Update the random Random -> Look at data -> Update the random Random`

https://pytorch.org/docs/stable/generated/torch.rand.html


In [ ]:
# Create the random Tensor
random_tensor=torch.rand(2,2,4,5)
random_tensor

tensor([[[[0.8529, 0.0371, 0.5449, 0.8835, 0.4288],
          [0.2770, 0.2100, 0.4999, 0.4741, 0.3636],
          [0.0629, 0.0079, 0.4197, 0.3737, 0.8530],
          [0.6228, 0.7582, 0.8800, 0.1445, 0.6934]],

         [[0.0175, 0.1359, 0.6423, 0.3190, 0.7890],
          [0.9113, 0.4360, 0.8676, 0.7573, 0.1962],
          [0.6909, 0.7253, 0.8036, 0.8862, 0.2953],
          [0.8813, 0.7131, 0.8194, 0.5944, 0.1300]]],


        [[[0.2913, 0.0413, 0.9994, 0.6109, 0.7803],
          [0.1396, 0.0598, 0.8662, 0.3042, 0.6068],
          [0.3369, 0.8818, 0.3109, 0.1887, 0.2012],
          [0.5871, 0.8653, 0.4973, 0.9352, 0.4504]],

         [[0.4300, 0.7461, 0.0622, 0.8014, 0.4629],
          [0.1812, 0.6907, 0.3256, 0.1296, 0.5328],
          [0.3672, 0.4465, 0.9240, 0.7066, 0.6622],
          [0.1291, 0.8969, 0.1607, 0.9845, 0.9585]]]])

In [ ]:
random_tensor.ndim

4

In [ ]:
#Craeting Random tensor as the same size of image data

random_tensor_image=torch.rand(size=(256,256,3))  #(width,height,color(R,G,B))
random_tensor_image.shape

torch.Size([256, 256, 3])

###Zeros and Ones

In [ ]:
#Create random number with zeros
zero=torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create the random number with ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###Creating a range of tensor

In [ ]:
#craete a range of number
one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Create the tensor like
ten_zeros=torch.zeros_like(input=(one_to_ten))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tenson DataType
**Note:** Tensor causes 3 common type of error.
1. Tensors are not same data type
2. Tensors are not same shape
3. Tensors are not Same type of device

https://pytorch.org/docs/stable/tensors.html

In [ ]:
 # Data Type
 tensor_float_32=torch.tensor([3.0,4.0,5.0],
                                            dtype=None,
                                            device=None,
                                            requires_grad=False)# wheather or not to track gradient with this tensor

In [ ]:
tensor_float_32.dtype

torch.float32

In [ ]:
tensor_float_16=tensor_float_32.type(torch.float16)
tensor_float_16

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
int_32_tensor=torch.tensor([23,12,78],dtype=torch.int32)
int_32_tensor

tensor([23, 12, 78], dtype=torch.int32)

In [ ]:
tensor_float_32*int_32_tensor

tensor([ 69.,  48., 390.])

### Getting Information from Tensors

1. Tensors are not same data type->To get data type from tensor, we can use `tensor.dtype`
2. Tensors are not same shape-> To get shape of the tensor, we can use `tensor.Shape`
3. Tensors are not Same type of device->To get Device name of the tensor,we can use `tensor.device`

In [ ]:
#create a tensor

some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.9150, 0.7498, 0.2431, 0.5474],
        [0.3364, 0.7409, 0.2928, 0.0190],
        [0.5054, 0.1738, 0.1209, 0.0792]])

In [ ]:
#find out detail about some_tensor
print(f"Data Type of tensor:{some_tensor.dtype}")
print(f"Shape of the Tensor :{some_tensor.shape}")
print(f"Device tensoris on :{some_tensor.device}")

Data Type of tensor:torch.float32
Shape of the Tensor :torch.Size([3, 4])
Device tensoris on :cpu


### Manipulating Tensors (Tensor Operations)
 Tensor Operations Include
 * Addition
 * Subtraction
 * Multiplication(Element Wise)
 * Division
 * Matrix Multiplication -> https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# create Tensor and add 10 to tensor
tensor=torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

In [ ]:
#Subtract 20 from tensor
tensor-20


tensor([-19, -18, -17])

In [ ]:
#Multiply by 10 to tensor
tensor * 10

tensor([10, 20, 30])

In [ ]:
#Multiplication using in-built funtion

torch.mul(tensor,2)  #torch.add(tensor,5)

tensor([2, 4, 6])

In [ ]:
#Element wise matrix multiplication
print(tensor,'*',tensor)
print(f"={tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
=tensor([1, 4, 9])


In [ ]:
#Dot Product of tensors
torch.matmul(tensor,tensor)  # 1*1 + 2*2 + 3*3 = 14

tensor(14)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 4.57 ms, sys: 198 µs, total: 4.77 ms
Wall time: 31 ms


In [ ]:
%%time
print(torch.matmul(tensor,tensor))

tensor(14)
CPU times: user 3.43 ms, sys: 52 µs, total: 3.48 ms
Wall time: 9.39 ms


*Transpose*

In [ ]:
tensor=torch.rand(2,3)
tensor=tensor.T
print(tensor.shape)

torch.Size([3, 2])


## Find the min, max, mean, sum etc(Tensor Aggregation)

In [ ]:
#Create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
#Find the Maximum
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
#Find the mean  --> note : torch.mean() require float32 datatype

torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#Find The sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

##Finding The positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Finding the position of  minimum value in tensor
x.argmin()

tensor(0)

In [ ]:
#Find the position of maximum value in tensor
x.argmax()

tensor(9)

##Reshaping,stacking,squeezing and unsqueezing tensors

* Reshaping - Changing the shape of the input tensor
* Skacking - Concatnate the tensors side by side or vertical or horizontly
* Sqeezing - Removeing all `1` dimentions from tensors
* Unsqueezing - Adding a `1` dimentions to target tensors
* View - Return a view of input tensor but keep the same  original tensors
* Permute - Return a view of input tensor with dimension permuted in certain way(swapped)

In [ ]:
#Lets Create a tensor
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the View
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z change x (Since z and x are sharing the same memory)
z[:,0]=20
z,x

(tensor([[20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [ ]:
# Stack the tensor top of each other
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[20., 20., 20., 20.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [ ]:
#Squeeze the tensor
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]), torch.Size([1, 9]))

In [ ]:
x_squeeze=x_reshaped.squeeze()
x_squeeze,x_squeeze.shape

(tensor([20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]), torch.Size([9]))

In [ ]:
#Unsqueeze the tensor
x_unsqueeze=x_squeeze.unsqueeze(dim=1)
x_unsqueeze,x_unsqueeze.shape

(tensor([[20.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]]),
 torch.Size([9, 1]))

In [ ]:
# Prermute the tensor
y=torch.rand(size=(224,224,3))   #[Height,width,color]
print(y.shape)
y_permuted=y.permute(2,0,1) #0->1 1->2 2->0
print(y_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


## Indexing(Selecting Data From Tensor)
Indexing in tensor is similar to Numpy


In [ ]:
#Lets create a tensor

import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Lets Index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Middle Bracket
x[0][1]

tensor([4, 5, 6])

In [ ]:
#Inner most Bracket
x[0][2][0]

tensor(7)

In [ ]:
# We can also use : to get target index
x[:,0:2,1:3]

tensor([[[2, 3],
         [5, 6]]])

In [ ]:
x[:,:,1]  #Its Like selecting the columns

tensor([[2, 5, 8]])

In [ ]:
print(x[0,0,:]) # Its like selecting 1st row
print(x[:,0,:])

tensor([1, 2, 3])
tensor([[1, 2, 3]])


In [ ]:
x[0,2,:]

tensor([7, 8, 9])

## Pytorch and Numpy
Numpy is popular scientific python numerical libraries and beacuse of this pytorch has functionality to interact with it.
* Numpy to Pytorch tensor-> `torch.from_numpy(ndarray)
* Pytorch tensor to Numpy -> `torch.Tensor.numpy()

In [ ]:
#Numpy to Tensor
import numpy as np
import torch

array=np.arange(1.0,10.0)
tensor=torch.from_numpy(array)

array,tensor

# Note:
# Numpy deafult data Type is float64 while for pytorch it is float32
# Since tensor is coverting from numpy that is why its data type become float64 to maintain compatibilty
#But we can change as:tensor=torch.from_numpy(array).type(torch.float32)

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
#Pytorch tensor to Numpy

X=torch.ones(8)
numpy_tensor=X.numpy()

X,numpy_tensor

# Note:
# Numpy deafult data Type is float64 while for pytorch it is float32
# Here numpy data type changed into float32

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## producibility (Random seed)


In [ ]:
import torch
tensor_A=torch.rand(3,4)
tensor_B=torch.rand(3,4)

print(tensor_A==tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Set the Random seed

torch.manual_seed(42)
tensor_A=torch.rand(3,4)

torch.manual_seed(42)
tensor_B=torch.rand(3,4)

print(tensor_A==tensor_B)



tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tenors and Pytorch objects on GPU



* Use Google Colab
* Use Cloud Computing -GCP,AWS,Azure   Allow to rent the Computers on cloud and access them

In [ ]:
!nvidia-smi


Sat Sep 21 16:11:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count Number of devices
torch.cuda.device_count()

1


###  Putting tensors (and models) on the GPU



In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

Notice the second tensor has device='cuda:0', this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be 'cuda:0' and 'cuda:1' respectively, up to 'cuda:n').

### Moving tensors back to the CPU

What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

Let's try using the `torch.Tensor.numpy()` method on our tensor_on_gpu.

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])